---
apiVersion: v2
description: A Helm chart for PowerDNS and PowerDNS-Admin with PostgreSQL backend, using the Helm "library chart" pattern from https://bjw-s.github.io/helm-charts and cloudnative-pg Postgres operator.
name: powerdns-authoritative
type: application
version: 0.1.0
appVersion: 4.9.0
kubeVersion: '>=1.26.0-0'
maintainers:
  - name: adamancini
    email: ada@annarchy.net
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.1.0
  - name: replicated
    version: '^1.0.0-beta.25'
    repository: 'oci://registry.replicated.com/library'
    condition: replicated.enabled
