---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix # or Absolute
        backend:
          service:
            name: frontend
            port:
              number: 80
