apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: cloudnative-pg
spec:
  chart:
    name: cloudnative-pg
    chartVersion: 0.21.5
  exclude: 'repl{{ ConfigOptionEquals `postgres_type` `external_postgres` }}'
  weight: 0
  values:
    image:
      repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "ghcr.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "cloudnative-pg" }}/cloudnative-pg'
