apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: powerdns
spec:
  title: App Name
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/powerdns
  ports:
    - serviceName: 'powerdns'
      servicePort: 8080
      localPort: 8888
      applicationUrl: 'http://pdns-admin'
