apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 1.21.0+k8s-1.30
  extensions:
    helm:
      repositories:
        - name: cnpg
          url: https://cloudnative-pg.github.io/charts
        - name: minio-operator
          url: https://operator.min.io
      charts:
        - name: cloudnative-pg
          chartname: cnpg/cloudnative-pg
          namespace: cnpg
          version: "0.22.1"
          values: |
            cloudnative-pg:
              enabled: true
        - name: minio-operator
          chartname: minio-operator/operator
          namespace: minio
          version: "6.0.4"
