{{- if .Values.postgres.embedded.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: pdns-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.auth.username }}
  password: {{ .Values.postgres.auth.password }}
{{- end }}
