apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 1.19.0+k8s-1.30
  roles:
    controller:
      name: controller
      labels:
        controller: "true"
    custom:
    - name: worker
      labels:
        worker: "true"
