# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json

#### PowerDNS User-Facing Application Configuration
# powerdns:

#### PowerDNS Workload Definitions
controllers:
  recursor:
    containers:
      main:
        image:
          repository: powerdns/pdns-recursor-50
          tag: 5.0.5
        env:
          - name: DEBUG_CONFIG
            value: 'yes'
    pod:
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE

configMap:
  config:
    99-recursor.conf: |
      allow-from=0.0.0.0
      local-address=0.0.0.0
      local-port=5353

persistence:
  recursor:
    type: configMap
    advancedMounts:
      recursor:
        main:
          - path: /etc/powerdns/recursor.d/99-recursor.conf
            configMap: recursor-config
            subpath: 99-recursor.conf

service:
  recursor:
    controller: recursor
    ports:
      udp:
        type: ClusterIP
        port: 53
        targetPort: 5353
        protocol: UDP
      tcp:
        type: ClusterIP
        port: 53
        targetPort: 5353
        protocol: TCP
