apiVersion: v1
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE9jCCA96gAwIBAgISBD3l+bMPuS8q0BrdTnUZc0DfMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTEwHhcNMjQxMjA1MTU1NDI2WhcNMjUwMzA1MTU1NDI1WjAeMRwwGgYDVQQD
    ExNjYXNzYW5kcmEueHl5engubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAuXHw2fd8ZcfRSQ/Lj3WQ4l/lagpC7sg3+z39ysXGHLksJqR7rOiFLuwN
    zszb101PyslNBST0F3BFDvgomuHdimNgL0tow8zBAuQRk+z/qwSmHSK34LwTLEqv
    Bbe3EIoEaEBKkQRUqa6mpDts+mJ7KXys+vZPSXCGcfxRME5FBHtp2WMydieY+1SD
    gi+6/0YbFL7i+nUSNLOJZ/kmTIoSn1tU/MaGLT/1QD9T9+X2J51ykQus7AgDq5ed
    9ZuqL14ygbwKgBVzKtODs+IMj5H2l7MZwY6Rz3dp/AJpOHPLimcB56Wx+IfW0895
    fdDKgLlK2qwkAOmqisX2gXLVCh+xZwIDAQABo4ICFzCCAhMwDgYDVR0PAQH/BAQD
    AgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA
    MB0GA1UdDgQWBBSTWNQFM9Zf0eSiKZMGEt+Fbyie2TAfBgNVHSMEGDAWgBTFz0ak
    6vTDwHpslcQtsF6SLybjuTBXBggrBgEFBQcBAQRLMEkwIgYIKwYBBQUHMAGGFmh0
    dHA6Ly9yMTEuby5sZW5jci5vcmcwIwYIKwYBBQUHMAKGF2h0dHA6Ly9yMTEuaS5s
    ZW5jci5vcmcvMB4GA1UdEQQXMBWCE2Nhc3NhbmRyYS54eXl6eC5uZXQwEwYDVR0g
    BAwwCjAIBgZngQwBAgEwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdwCi4wrkRe+9
    rZt+OO1HZ3dT14JbhJTXK14bLMS5UKRH5wAAAZOXvSrYAAAEAwBIMEYCIQCgoyeZ
    KNU3HCi0qTYmvsyXXmquMPJfCBEFfCg05zduWAIhAKxuNAle4oy/HBR3hvZqycXL
    KQ1OcwEV6Xr0/Gqhiay6AHUAfVkeEuF4KnscYWd8Xv340IdcFKBOlZ65Ay/ZDowu
    ebgAAAGTl70q4gAABAMARjBEAiACMqaresnlxQWUwGxrqcORe855FcDd6VclM266
    lxYvmAIgFul8XhYzsRDmkjYPNRpqbGVrI8s8vSONXiJ0ocuIM0UwDQYJKoZIhvcN
    AQELBQADggEBAA4NzcnjFFSwB6/FLps4i8Pz+vap3hzaPs9Me8oRjg1lkcwpE1I9
    J/yGO8OoCzhl4l406S2TYsT8zIt/4M+2US8tyRa0hpHtngbe/EzOyxD6oLCJ/lN4
    HjsW4ztD8jii1novIlxbdqjBooitVjE6z4+rC7+BtlXKIr34ZibIXg9TE+bHiSyX
    +kK5ZzbcDErcAbeFbypDOO3Yw93Ag/D6crz/mrP9t3c7dQzmUuy80oEJ2YmBLX6M
    AP6ub1dyYvGCldWdpl3K5lATwEppmOZBchIk+i6Fqvh2PlTqORG5AJOqykyIjq0P
    QdmgkAkdTSsz4SYpDumEpztGZqZF1DJSzLY=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFBjCCAu6gAwIBAgIRAIp9PhPWLzDvI4a9KQdrNPgwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
    WhcNMjcwMzEyMjM1OTU5WjAzMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDEMMAoGA1UEAxMDUjExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAuoe8XBsAOcvKCs3UZxD5ATylTqVhyybKUvsVAbe5KPUoHu0nsyQYOWcJ
    DAjs4DqwO3cOvfPlOVRBDE6uQdaZdN5R2+97/1i9qLcT9t4x1fJyyXJqC4N0lZxG
    AGQUmfOx2SLZzaiSqhwmej/+71gFewiVgdtxD4774zEJuwm+UE1fj5F2PVqdnoPy
    6cRms+EGZkNIGIBloDcYmpuEMpexsr3E+BUAnSeI++JjF5ZsmydnS8TbKF5pwnnw
    SVzgJFDhxLyhBax7QG0AtMJBP6dYuC/FXJuluwme8f7rsIU5/agK70XEeOtlKsLP
    Xzze41xNG/cLJyuqC0J3U095ah2H2QIDAQABo4H4MIH1MA4GA1UdDwEB/wQEAwIB
    hjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB
    /wIBADAdBgNVHQ4EFgQUxc9GpOr0w8B6bJXELbBeki8m47kwHwYDVR0jBBgwFoAU
    ebRZ5nu25eQBc4AIiMgaWPbpm24wMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAC
    hhZodHRwOi8veDEuaS5sZW5jci5vcmcvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMCcG
    A1UdHwQgMB4wHKAaoBiGFmh0dHA6Ly94MS5jLmxlbmNyLm9yZy8wDQYJKoZIhvcN
    AQELBQADggIBAE7iiV0KAxyQOND1H/lxXPjDj7I3iHpvsCUf7b632IYGjukJhM1y
    v4Hz/MrPU0jtvfZpQtSlET41yBOykh0FX+ou1Nj4ScOt9ZmWnO8m2OG0JAtIIE38
    01S0qcYhyOE2G/93ZCkXufBL713qzXnQv5C/viOykNpKqUgxdKlEC+Hi9i2DcaR1
    e9KUwQUZRhy5j/PEdEglKg3l9dtD4tuTm7kZtB8v32oOjzHTYw+7KdzdZiw/sBtn
    UfhBPORNuay4pJxmY/WrhSMdzFO2q3Gu3MUBcdo27goYKjL9CTF8j/Zz55yctUoV
    aneCWs/ajUX+HypkBTA+c8LGDLnWO2NKq0YD/pnARkAnYGPfUDoHR9gVSp/qRx+Z
    WghiDLZsMwhN1zjtSC0uBWiugF3vTNzYIEFfaPG7Ws3jDrAMMYebQ95JQ+HIBD/R
    PBuHRTBpqKlyDnkSHDHYPiNX3adPoPAcgdF3H2/W0rmoswMWgTlLn1Wu0mrks7/q
    pdWfS6PJ1jty80r2VKsM/Dj3YIDfbjXKdaFU5C+8bhfJGqU3taKauuz0wHVGT3eo
    6FlWkWYtbt4pgdamlwVeZEW+LM7qZEJEsMNPrfC03APKmZsJgpWCDWOKZvkZcvjV
    uYkQ4omYCTX5ohy+knMjdOmdH9c7SpqEWBDC86fiNex+O0XOMEZSa8DA
    -----END CERTIFICATE-----

  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE9jCCA96gAwIBAgISBD3l+bMPuS8q0BrdTnUZc0DfMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTEwHhcNMjQxMjA1MTU1NDI2WhcNMjUwMzA1MTU1NDI1WjAeMRwwGgYDVQQD
    ExNjYXNzYW5kcmEueHl5engubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAuXHw2fd8ZcfRSQ/Lj3WQ4l/lagpC7sg3+z39ysXGHLksJqR7rOiFLuwN
    zszb101PyslNBST0F3BFDvgomuHdimNgL0tow8zBAuQRk+z/qwSmHSK34LwTLEqv
    Bbe3EIoEaEBKkQRUqa6mpDts+mJ7KXys+vZPSXCGcfxRME5FBHtp2WMydieY+1SD
    gi+6/0YbFL7i+nUSNLOJZ/kmTIoSn1tU/MaGLT/1QD9T9+X2J51ykQus7AgDq5ed
    9ZuqL14ygbwKgBVzKtODs+IMj5H2l7MZwY6Rz3dp/AJpOHPLimcB56Wx+IfW0895
    fdDKgLlK2qwkAOmqisX2gXLVCh+xZwIDAQABo4ICFzCCAhMwDgYDVR0PAQH/BAQD
    AgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA
    MB0GA1UdDgQWBBSTWNQFM9Zf0eSiKZMGEt+Fbyie2TAfBgNVHSMEGDAWgBTFz0ak
    6vTDwHpslcQtsF6SLybjuTBXBggrBgEFBQcBAQRLMEkwIgYIKwYBBQUHMAGGFmh0
    dHA6Ly9yMTEuby5sZW5jci5vcmcwIwYIKwYBBQUHMAKGF2h0dHA6Ly9yMTEuaS5s
    ZW5jci5vcmcvMB4GA1UdEQQXMBWCE2Nhc3NhbmRyYS54eXl6eC5uZXQwEwYDVR0g
    BAwwCjAIBgZngQwBAgEwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdwCi4wrkRe+9
    rZt+OO1HZ3dT14JbhJTXK14bLMS5UKRH5wAAAZOXvSrYAAAEAwBIMEYCIQCgoyeZ
    KNU3HCi0qTYmvsyXXmquMPJfCBEFfCg05zduWAIhAKxuNAle4oy/HBR3hvZqycXL
    KQ1OcwEV6Xr0/Gqhiay6AHUAfVkeEuF4KnscYWd8Xv340IdcFKBOlZ65Ay/ZDowu
    ebgAAAGTl70q4gAABAMARjBEAiACMqaresnlxQWUwGxrqcORe855FcDd6VclM266
    lxYvmAIgFul8XhYzsRDmkjYPNRpqbGVrI8s8vSONXiJ0ocuIM0UwDQYJKoZIhvcN
    AQELBQADggEBAA4NzcnjFFSwB6/FLps4i8Pz+vap3hzaPs9Me8oRjg1lkcwpE1I9
    J/yGO8OoCzhl4l406S2TYsT8zIt/4M+2US8tyRa0hpHtngbe/EzOyxD6oLCJ/lN4
    HjsW4ztD8jii1novIlxbdqjBooitVjE6z4+rC7+BtlXKIr34ZibIXg9TE+bHiSyX
    +kK5ZzbcDErcAbeFbypDOO3Yw93Ag/D6crz/mrP9t3c7dQzmUuy80oEJ2YmBLX6M
    AP6ub1dyYvGCldWdpl3K5lATwEppmOZBchIk+i6Fqvh2PlTqORG5AJOqykyIjq0P
    QdmgkAkdTSsz4SYpDumEpztGZqZF1DJSzLY=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQC5cfDZ93xlx9FJ
    D8uPdZDiX+VqCkLuyDf7Pf3KxcYcuSwmpHus6IUu7A3OzNvXTU/KyU0FJPQXcEUO
    +Cia4d2KY2AvS2jDzMEC5BGT7P+rBKYdIrfgvBMsSq8Ft7cQigRoQEqRBFSprqak
    O2z6YnspfKz69k9JcIZx/FEwTkUEe2nZYzJ2J5j7VIOCL7r/RhsUvuL6dRI0s4ln
    +SZMihKfW1T8xoYtP/VAP1P35fYnnXKRC6zsCAOrl531m6ovXjKBvAqAFXMq04Oz
    4gyPkfaXsxnBjpHPd2n8Amk4c8uKZwHnpbH4h9bTz3l90MqAuUrarCQA6aqKxfaB
    ctUKH7FnAgMBAAECggEAEbAfg/rKH78mZCyggud40U7KSAoAhlwMkuc/zNZ+ZgD3
    iBwKO9zVzzruujnqAig6oyH+Oa5jpdSskZfz74n5opiF9RzhOkPOaSMt1gk1/a7s
    1TyZg1MNFR1ugkIasPYpI3R2aEyccq7Y8DNG2r8H9lYQ/cL+nwefm0Gw0MW2aY3e
    QoBIxPYrFQLg14WemptHbYKP73E7mDjwxXPDQnL4zDJb1EHfEsmjH+ocBkGBfQSF
    izfLQZbc4yiyuTXHD811QS4rB6aAN3DLnt9SmBRvHZzRBNMnKuD9VFHpXUUuOVrO
    JZCWtbkyntPUHM0EsNglYOXOZENneh0DvBx8xaE3cQKBgQDroP/QPKUXxMRjho2W
    qgIUte1U5lbsXfI3SxbU6ru5Jm7QVL3SyxpklREAAhCI3IRgUGIB32HcXbkjktc8
    uQrf6VK42wgZ58BO8idOd6G7JsTJ/2NyUEbMy9bWgdhDoljeNWWQQTmY62RTU/mA
    SEW5szbj/wjwboXhUnf7ifBl2QKBgQDJekKRo3/2vf9mxmp7JSZ0gLp63wkDqkH/
    Kn/rJ1CnPG3jmim8kifxqjBBWjrWkC+dGG7B97eKCsNpo71p1aTRUfRD7smd+/q2
    oj0UCc7t1RsWuZol7NtXJSTUJkPpRZd6DU0FUpBeGKSw7cxA2Qldl4o/TuttLbeh
    z//uwDIJPwKBgGSJdn0oUxzYJR9+Gs2tTmP91/0ApxgFYcL79Ar2+RAf+OpFLhVR
    +bnu7Kj/OITc6lKaGadI49190+/8yH+tSJmPWW9sbYF4I9LLeb/+RXCwMwkpQgpV
    fFAHrWwrTNZW3+o4CFTLr8KytUTksLFupOl+MS6I9Ax6a/9fC7i0+3DJAoGBAIPs
    82Pr3GGTvYXtjFHAXLLSi8ji/EMTHA3aJVK0NqKa9hWfn46jYVZjqx9P1tEiLps+
    IWAPNXZFX/lvRxri0v5hHIHS/N/e3Cb0iuvxFDc1YHx74czNkD46yyfDOpqnf+1i
    gjlm+7Mxjb1wqFsaAoDvNo4Hvi6KTgC9cwdBgEH/An81lp3p8VW6dxyMkK8ExKW/
    vI+JZ3vkgqnqP8buG3+Az5DcVj/bWiOG5Bfd6+0jOFkjgzHFXX2+9DyN4YJok3+U
    P0HO3H4EAV1leQqCYDR0ogpHzyp31witefy3028ICnVJ9Co+SAkiDsnnQom0a9UZ
    AlDyFs4BEUfn39bygOCu
    -----END PRIVATE KEY-----
kind: Secret
metadata:
  name: cassandra-tls-certs
type: kubernetes.io/tls
