apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 1.20.0+k8s-1.30-rc1
  extensions:
    helm:
      repositories:
        - name: cnpg
          url: https://cloudnative-pg.github.io/charts
      charts:
        - name: cloudnative-pg
          chartname: cnpg/cloudnative-pg
          namespace: cnpg
          version: "0.22.1"
          values: |
            cloudnative-pg:
              enabled: true
        - name: minio-operator
          chartname: minio-operator/operator
          namespace: minio
          version: "6.0.4"
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          api:
            extraArgs:
              service-node-port-range: 80-32767
