---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config
spec:
  groups:
  # cassandra settings
  - name: cassandra_settings
    title: Cassandra Settings
    items:
    - name: cassandra_user
      title: Cassandra User
      type: text
      default: cassandra
      required: true
      description: The username to use for the Cassandra user
    - name: cassandra_password
      title: Cassandra Password
      type: text
      default: cassandra
      required: true
      description: The password to use for the Cassandra user
      secret: true
    - name: cassandra_truststore_password
      title: Cassandra Truststore Password
      type: text
      default: cassandra
      required: true
      description: The password to use for the Cassandra truststore
      secret: true
    - name: cassandra_keystore_password
      title: Cassandra Keystore Password
      type: text
      default: cassandra
      required: true
      description: The password to use for the Cassandra keystore
      secret: true
    - name: cassandra_tls_cert
      title: Cassandra TLS Certificate
      type: textarea
      default: ""
      required: true
      description: The TLS certificate to use for the Cassandra client encryption
    - name: cassandra_tls_key
      title: Cassandra TLS Key
      type: textarea
      default: ""
      required: true
      description: The TLS key to use for the Cassandra client encryption
      secret: true
    - name: cassandra_tls_ca
      title: Cassandra TLS CA
      type: textarea
      default: ""
      required: true
      description: The root CA to use for the Cassandra client encryption
