name: Compatibilty Test with CMX

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Run tests'
        required: true
        default: 'true'

jobs:
  compatibility-matrix:
    strategy:
      fail-fast: false
      matrix:
        cluster: [ {distribution: kind, version: v1.25.3}, {distribution: k3s, version: v1.26}]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          helm package . -u

      - name: Prepare Cluster
        id: prepare-cluster
        uses: replicatedhq/replicated-actions/prepare-cluster@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          chart: mlflow-0.2.0.tgz
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          helm-chart-name: mlflow
